BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MAJORATION_DIFFUSION DROP CONSTRAINT MAJORATION_DIFFUSION_TAUX_CHK';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE MAJORATION_DIFFUSION
    ADD CONSTRAINT MAJORATION_DIFFUSION_TAUX_CHK
        CHECK (TAUXMAJORATION >= -100);
