CREATE TABLE MAJORATION_DIFFUSION
(
    ID             VARCHAR2(100) NOT NULL,
    JOUR           VARCHAR2(20)  NOT NULL,
    HEUREDEBUT     VARCHAR2(8)   NOT NULL,
    HEUREFIN       VARCHAR2(8)   NOT NULL,
    TAUXMAJORATION NUMBER(10,4) DEFAULT 0 NOT NULL
);

ALTER TABLE MAJORATION_DIFFUSION
    ADD CONSTRAINT MAJORATION_DIFFUSION_PK
        PRIMARY KEY (ID);

ALTER TABLE MAJORATION_DIFFUSION
    ADD CONSTRAINT MAJORATION_DIFFUSION_JOUR_CHK
        CHECK (JOUR IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'));

ALTER TABLE MAJORATION_DIFFUSION
    ADD CONSTRAINT MAJORATION_DIFFUSION_TAUX_CHK
        CHECK (TAUXMAJORATION >= -100);

CREATE SEQUENCE seq_majoration_diffusion
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE FUNCTION getseq_majoration_diffusion
RETURN NUMBER
IS
  retour NUMBER;
BEGIN
  SELECT seq_majoration_diffusion.NEXTVAL INTO retour FROM dual;
  RETURN retour;
END;
/
SHOW ERRORS;
